### ISSUE TITLE
[Todo, Paging] 코드 리펙토링

### ISSUE THREAD

**Issue by coolOlive** [Sppringkler/Sandbox_babac_jjeon#19]
## 💜 어떤 기능인가요?
---
- 코드 리뷰를 바탕으로 리펙토링을 진행합니다.

## ✅ To Dos
- [x] controller - service 로직 분리
- [x] dto 생성(응답, 요청 객체)
- [x] 보안 관련 요소 고민하기
- [x] 협업 관련 요소 고민하기 (코드 컨벤션, 불필요한 import 삭제 등등)

## ✅ Paging
- [x] controller - service 로직 분리
- [x] 디렉토리 구조 협의
- [x] 각 계층 별, 객체별 역할 논의
- [x] 보안 요소 고민하기
- [x] 협업 관련 요소 고민하기
