### ISSUE TITLE
[todos] read기능 구현

### ISSUE THREAD

**Issue by coolOlive** [Sppringkler/Sandbox_babac_jjeon#9]
## 💜 어떤 기능인가요?
---
sandbox의 todo list에 대한 CRUD를 개발합니다.

## ✅ ToDos
1.  개발 환경 세팅
    - [x] 인텔리제이에 스프링 프로젝트 세팅
    - [x] 깃 세팅
    - [x] 데이터베이스 만들기 
    - [x] sandbox에 연결되도록 하기
2. Read
    - [x] 성공시 리스트 보이기
    - [x] 실패일 때 처리하기
3. Delete
    - [x] 성공 시 삭제
    - [x] 실패일 때 처리하기
4.  Update
    - [x] 성공 시 수정
    - [x] 실패일 때 처리하기
5.  Create
    - [x] 성공 시 추가
    - [x] 실패일 때 처리하기

**Comment by coolOlive** [comment]
CRUE 작업 완료!
